### PR TITLE
implements support for DriveInfo

### PR DESCRIPTION
**Pull request by manne**

### CODE REVIEW

**Comment by manne** [comment]
@tathamoddie can you take a look at this pr. thank you

**Comment by manne** [comment]
should meet the requirements of #141

**Comment by damanptyltd** [comment]
This code looks great, why has it not been merged yet?

**Comment by tathamoddie** [comment]
Published as 2.0.0.124.

Sorry, it took me a while to review and click the button.

This project often outstrips my ability to coordinate and review PRs. Interested in finding another trusted maintainer over time.

**Pull request merged**
