### PR TITLE
NET Standard compatibility v2

### PR DESCRIPTION
**Pull request by alistair**
This is the code changes in #221 with appveyor working (hopefully)

### CODE REVIEW

**Comment by alistair** [comment]
Hi @tathamoddie.

I have got the following working using both net40 and netstandard targets.   I would love some feedback on whether this can be merged.   There are still things to do,  like fix some of the tests which are using BinarySerialiser which isnt supported on netstandard.

Also some of the original api I believe is also not available on netstandard,  but I think this is a good start

**Comment by gabrielsadaka** [comment]
@alistair @tathamoddie  Are there any more changes needed for the PR to get it merged? Happy to help out to get this ready for .Net Standard v2 if needed.

**Comment by wertzui** [comment]
Would be happy if this one gets merged, I need netstandard support oo.

**Comment by robichaud** [comment]
@tathamoddie is there anything we can do to help move this forward?

**Comment by seanamosw** [comment]
Could really use this as well. Have some projects that are blocked from moving to core/standard.

**Comment by jpreese** [comment]
+1 trying to use this in a netcoreapp

**Comment by mcattle** [comment]
+1 I, too, am waiting for this PR to be merged, so I can use it in a .NET Core 2.0 app.

**Comment by tathamoddie** [comment]
Should now be available in 2.1+ on NuGet.

More detailed discussion about the future in #229

**Comment by mcattle** [comment]
Timely merge, thanks!

**Comment by RussKie** [comment]
This change has caused a regression - the assembly is no longer marked as CLS compliant:

image

image

image

**Pull request merged**
