### PR TITLE
#186: Fixed difference in behavior of GetDirectories with absolute or relative paths

### PR DESCRIPTION
**Pull request by MCCoolMoDAue**
I've added tests and everything works,
but I don't know if the change I made is acceptable.
this should fix [Issue#169](https://github.com/tathamoddie/System.IO.Abstractions/issues/169)

feel free to correct me.

### CODE REVIEW

**Comment by AlexanderPruss** [comment]
On my setup, I had to add [Test] attributes to a couple of tests to get them to run in TypeMock's test runner. It's a Typemock error - the tests still ran fine as NUnit tests directly - but it'd be a nice addition IMO.

I ended up doing this on my fork here: https://github.com/AlexanderPruss/System.IO.Abstractions---Consistency-with-MSCORLIB-fixes/commit/bc08b340a2930c3d4c3d99fb49dfc917b90e0cf0

**Comment by MCCoolMoDAue** [comment]
I think the test runner fixes should be a separate pull request. Maybe you
can create an issue for that?
I can't fix it because I have a different test runner.

I am more interested if my solution is acceptable or not.
Any opinion?

**Comment by MCCoolMoDAue** [comment]
@tathamoddie  please look into this. If i can change anything to get this merged, please tell me.

**Comment by zvirja** [comment]
@tathamoddie Could you please clarify what is the status of the project? Is it still alive?

The issue this PR addresses is critical, while it's still not merged. Let us know whether we need to apply any changes to be merged.

Thank you! 😉

**Comment by tathamoddie** [comment]
Fixing in #258, based on these changes but rebased on top of newer ones

**Comment by zvirja** [comment]
@MCCoolMoDAue @tathamoddie Thank you guys for fixing and releasing this one! :innocent:

**Comment by MCCoolMoDAue** [comment]
my pleasure!

2017-11-07 10:14 GMT+01:00 Alex Povar <notifications@github.com>:

**Pull request closed without merging**
